### ISSUE TITLE
A great alternative to Ipstack

### ISSUE THREAD

**Issue by laurentpellegrino** [mattosaurus/IpStack#1]
A small message to let you discover an alternative to Ipstack you might like: Ipregistry (https://ipregistry.co). The API is about 5 times faster Worldwide than Ipstack, provides more data points and provide better accuracy in most cases. Last but not least, it includes a large free tier. 

Feel free to close this issue if you think it does not worth a look.

**Comment by mattosaurus** [comment]
Thanks, I'll definitely take a look at this.

**Comment by mattosaurus** [comment]
So, it's taken me a little while but I've finally gotten around to creating a client library for accessing the ipregistry API. It certainly seems like a better option than IpStack and the size of the free tier is much appreciated.

https://github.com/mattosaurus/IpRegistry

I've published this to NuGet as well.
