### ISSUE TITLE
Does not work with RestSharp 106.6.10

### ISSUE THREAD

**Issue by jonesty** [mattosaurus/IpStack#2]
When using with RestSharp 106.6.10, making a call to GetIpAddressDetails fails with the following exception: Could not load type 'RestSharp.Deserializers.JsonDeserializer' from assembly 'RestSharp, Version=106.6.10.0, Culture=neutral, PublicKeyToken=598062e77f915f75'.

This type now appears to live in a different namespace (RestSharp.Serialization.Json).

**Comment by jonesty** [comment]
@mattosaurus Are you still maintaining this repo mate?

**Comment by mattosaurus** [comment]
I haven't used it for a while but am still happy to make changes, am on holiday at the moment so won't have a chance to look at this until next week.

Feel free to submit a PR or I'll have a look at it then.

**Comment by jonesty** [comment]
No worries, thanks mate. I'll see how I go for time this week regarding the PR.

**Comment by jonesty** [comment]
PR #3 created. It was just a simple namespace change.

**Comment by mattosaurus** [comment]
Awesome, thanks for this. Just realised I can't publish this until I'm back on Saturday, hope that's ok.

**Comment by jonesty** [comment]
All good, cheers.

**Comment by mattosaurus** [comment]
I've just published v1.0.1 with the update, let me know if al is good for you now.

**Comment by jonesty** [comment]
All good, thanks!
