### ISSUE TITLE
System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by xbaha** [mattosaurus/IpStack#4]
got this error:

System.IO.FileNotFoundException: 'Could not load file or assembly 'RestSharp, Version=106.6.10.0, Culture=neutral, PublicKeyToken=598062e77f915f75'. The system cannot find the file specified.'

not sure where to look?

**Comment by mattosaurus** [comment]
What version of the package are you using?

I fixed this in 1.0.1 which was mentioned in #2

**Comment by xbaha** [comment]
i am using the latest, just installed it today.
Anyway, i found out the issue:
if i install both, this plugin and RestSharp, i get this error, i have to uninstall RestSharp for this to work.
i think your package is installing another RestSharp version, thus there is a conflict.
