### ISSUE TITLE
JsonException - Can't convert 'Connection.Asn' to int for value 'Null'

### ISSUE THREAD

**Issue by scottiebrady** [mattosaurus/IpStack#5]
When doing an IP Address look up for '89.40.212.239' it returns the http response:

`{"ip": "89.40.212.239", "type": "ipv4", "continent_code": "EU", "continent_name": "Europe", "country_code": "GB", "country_name": "United Kingdom", "region_code": "WLS", "region_name": "Wales", "city": "Chepstow", "zip": "BS32", "latitude": 51.57699966430664, "longitude": -2.565999984741211, "location": {"geoname_id": 2653256, "capital": "London", "languages": [{"code": "en", "name": "English", "native": "English"}], "country_flag": "https://assets.ipstack.com/flags/gb.svg", "country_flag_emoji": "\ud83c\uddec\ud83c\udde7", "country_flag_emoji_unicode": "U+1F1EC U+1F1E7", "calling_code": "44", "is_eu": true}, "time_zone": {"id": "Europe/London", "current_time": "2023-06-23T01:22:17+01:00", "gmt_offset": 3600, "code": "BST", "is_daylight_saving": true}, "currency": {"code": "GBP", "name": "British Pound Sterling", "plural": "British pounds sterling", "symbol": "\u00a3", "symbol_native": "\u00a3"}, "connection": {"asn": null, "isp": null}}`

You can see the 'connection' property is being returned but with value:
`"connection": {"asn": null, "isp": null}`

Looking at the Asn property it is an 'int', so as a result it throws an exception. Ideally the http response should return the 'connection' as null, but guessing they won't want to change that. Instead can we make the Asn property a nullable int so that it doesn't throw an exception?

**Comment by mattosaurus** [comment]
Hi, I've published v2.1.0 to hopefully fix this.

Thanks for pointing it out.

**Comment by scottiebrady** [comment]
Hi @mattosaurus, thanks for the quick fix. I've tested the latest package and no longer getting the JsonException.
